name: Build Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: Build for Android 📱
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Unity Builder
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: Android
          androidExportType: 'androidPackage'
          buildName: AlphamixGame
          # अगर आपका Unity प्रोजेक्ट किसी फोल्डर के अंदर है, तो उसका नाम नीचे लिखें
          # अगर रूट पर ही है, तो इसे '.' रहने दें
          projectPath: . 

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Game-APK
          path: build/Android/*.apk
          
